id: P006933
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:32.242226
source_metadata:
  id: bdr:W1AC400
  title: 'ཀཾ་ཚང་བླ་མ་ཡབ་སྲས་དྲུག་གི་རྣམ་ཐར། '
  author: ''
  volumes:
    15caf83bd25a42f5b9414e3ecf78369d:
      image_group_id: I2PD18755
      title: Volume 1 of kaM tshang bla ma yab sras drug gi rnam thar/
      volume_number: 1
      total_pages: 140
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
