id: P006933
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC400
  title: 'ཀཾ་ཚང་བླ་མ་ཡབ་སྲས་དྲུག་གི་རྣམ་ཐར། '
  author: ''
  volumes:
    fc5d2d3da1b64d50a352573d767afd34:
      image_group_id: I2PD18755
      title: ''
      volume_number: 1
      total_pages: 140
ebook_metadata:
  title: 'ཀཾ་ཚང་བླ་མ་ཡབ་སྲས་དྲུག་གི་རྣམ་ཐར། '
  author: ''
  sku: P006933
  cover: cover.jpg
  layers:
  - pagination
